### ISSUE TITLE
I don't know what the problem is. What do I need to fix?

### ISSUE THREAD

**Issue by L33S3H** [yenchenlin/nerf-pytorch#102]
(sehyun) C:\Windows\System32\nerf-pytorch>python run_nerf.py --config configs/lego.txt
Traceback (most recent call last):
  File "C:\Windows\System32\nerf-pytorch\run_nerf.py", line 878, in <module>
    train()
  File "C:\Windows\System32\nerf-pytorch\run_nerf.py", line 570, in train
    images, poses, render_poses, hwf, i_split = load_blender_data(args.datadir, args.half_res, args.testskip)
  File "C:\Windows\System32\nerf-pytorch\load_blender.py", line 41, in load_blender_data
    with open(os.path.join(basedir, 'transforms_{}.json'.format(s)), 'r') as fp:
FileNotFoundError: [Errno 2] No such file or directory: './data/nerf_synthetic/lego\\transforms_train.json'

**Comment by jamesdemon923** [comment]
Hi! How did you solve this problem? Thanks!

**Comment by JY251** [comment]
This issue is due to the lack of example data. To resolve this, please run the following command to download the example data first:
```
bash download_example_data.sh
```
After downloading the data, you should be able to run the command successfully:
```
python run_nerf.py --config configs/lego.txt
```
These steps are mentioned in [README.md](https://github.com/yenchenlin/nerf-pytorch?tab=readme-ov-file#quick-start)
