### ISSUE TITLE
Why no_batching=True when using blender data type?

### ISSUE THREAD

**Issue by sstzal** [yenchenlin/nerf-pytorch#37]
Hi,

I'm a little confused about the config setting: Why no_batching=True when using blender data type? Are there any special considerations for doing this?

I notice that when no_batching=True, the code will sample rays near the center of the image, and I'm confused about why doing such operation with blender data rather than llff data type?

Thanks

**Comment by yenchenlin** [comment]
> I'm a little confused about the config setting: Why no_batching=True when using blender data type? Are there any special considerations for doing this?

[Here](https://github.com/bmild/nerf/issues/108) is the authors' answer on setting `no_batching`'s value. 

Note that `no_batching` has no relationship with "sample rays near the center of the image". This behavior comes from [these two lines](https://github.com/yenchenlin/nerf-pytorch/blob/master/configs/chair.txt#L16-L17) in the config. I added it because I found that synthetic images have a large portion of white background and sampling those pixels too much may cause NeRFs to always predict white colors.
